version: '3'

services:
  mark:
    build: .
    environment:
      - HOSTPORT=0.0.0.0:5051
      - NEIGHBOURS=lucy:5051,ken:5051,kate:5051,sally:5051
    volumes:
      - ./log:/app/log
    command: "./main"

  lucy:
    build: .
    environment:
      - HOSTPORT=0.0.0.0:5051
      - NEIGHBOURS=mark:5051,ken:5051,kate:5051,sally:5051
    volumes:
      - ./log:/app/log
    command: "./main"

  ken:
    build: .
    environment:
      - HOSTPORT=0.0.0.0:5051
      - NEIGHBOURS=mark:5051,lucy:5051,kate:5051,sally:5051
    volumes:
      - ./log:/app/log
    command: "./main"
  
  kate:
    build: .
    environment:
      - HOSTPORT=0.0.0.0:5051
      - NEIGHBOURS=mark:5051,ken:5051,lucy:5051,sally:5051
    volumes:
      - ./log:/app/log
    command: "./main"
  
  sally:
    build: .
    environment:
      - HOSTPORT=0.0.0.0:5051
      - NEIGHBOURS=mark:5051,ken:5051,kate:5051,lucy:5051
    volumes:
      - ./log:/app/log
    command: "./main"
